# rabbitmq SERVER

BROKER_URL = 'amqp://guest:guest@0.0.0.0:5672//'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TRACK_STARTED = True
CELERY_ENABLE_UTC = True
CELERY_RESULT_BACKEND = 'django-db'

# # CELERY ROUTES
CELERY_ROUTES = {
}
